DPEnergy/Areas/AdminArea/Controllers/AccessRightController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DPEnergy.DataModelLayer.Entities.Admin;
using DPEnergy.DataModelLayer.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using DPEnergy.DataModelLayer.ViewModels;
using DPEnergy.DataModelLayer.Entities;
using Microsoft.AspNetCore.Authorization;

namespace DPEnergy.Areas.AdminArea.Controllers
{
    [Area("AdminArea")]
    [Authorize(Roles = "AdminArea")]
    public class AccessRightController : Controller
    {
        //دارای یک نکته مهم
        private readonly IUnitOfWork _context;
        private readonly IRoleRepository _Irr;
        private readonly UserManager<A_UserManager> _userManager;
        private readonly RoleManager<ApplicationRoles> _roleManager;
        private readonly IAccessRepository _getname;
        private readonly SignInManager<A_UserManager> _signInManager;

        public AccessRightController(IUnitOfWork context,
                                    UserManager<A_UserManager> userManager,
                                    RoleManager<ApplicationRoles> roleManager,
                                    IRoleRepository irr,
                                    IAccessRepository getname,
                                    SignInManager<A_UserManager> signInManager)
        {
            _context = context;
            _userManager = userManager;
            _roleManager = roleManager;
            _Irr = irr;
            _getname = getname;
            _signInManager = signInManager;
        }

        public IActionResult Index()
        {
            var model = _getname.GetNameFromPersonelCode(); 
            return View(model);
        }

        [HttpGet]
        public IActionResult AddRoleToUser( string id , string firstname , string lastname)
        {
            FillTreeView();
            ViewBag.FullName = firstname + " " + lastname;
            ViewBag.userId = id;
            ViewBag.userRole = _Irr.GetRoleId(id);
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddRoleToUser(string selectedItems, string userId)
        {
            try
            {
                //تبدیل رشته جیسون به یک لیست
                List<TreeViewModel> items = JsonConvert.DeserializeObject<List<TreeViewModel>>(selectedItems);
                if (items.Count() == 0)
                {
                    return Json(new { status = "noselected" });
                }

                //پیدا کردن کاربر
                var user = await _userManager.FindByIdAsync(userId);

                //پیدا کردن همه نقش های کاربر
                var roles = await _userManager.GetRolesAsync(user);
                //حذف همه دسترسی های قبلی کاربر
                IdentityResult deleteAllrole = await _userManager.RemoveFromRolesAsync(user, roles);


                if (deleteAllrole.Succeeded)
                {
                    //ثبت دسترسی های جدید به کاربر
                    for (int i = 0; i <= items.Count - 1; i++)
                    {
                        ApplicationRoles approle = await _roleManager.FindByIdAsync(items[i].id);
                        if (approle != null)
                        {
                            await _userManager.AddToRoleAsync(user, approle.Name);
                        }
                    }
                    await _signInManager.RefreshSignInAsync(user);
                }
                return Json(new { status = "success" });

            }
            catch
            {
                return RedirectToAction("ErrorView", "Home");
            }

        }
        private void FillTreeView()
        {
            List<TreeViewModel> node = new List<TreeViewModel>();

            node.Add(new TreeViewModel
            {
                id = "1",
                text = "حقوق دسترسی",
                parent = "#"
            });

            foreach (ApplicationRoles role in _context.RoleManagerUW.Get(r => r.RoleLevel != "0"))
            {
                node.Add(new TreeViewModel
                {
                    id = role.Id.ToString(),
                    parent = role.RoleLevel.ToString(),
                    text = role.Description
                });
            }

            ViewBag.AccessRight = JsonConvert.SerializeObject(node);
        }

       

       
    }
}

DPEnergy/Areas/AdminArea/Controllers/UserManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using DPEnergy.DataModelLayer.Entities;
using DPEnergy.DataModelLayer.Entities.Admin;
using DPEnergy.DataModelLayer.Services;
using DPEnergy.DataModelLayer.ViewModels.Admin;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace DPEnergy.Areas.AdminArea.Controllers
{
    [Area("AdminArea")]
    [Authorize(Roles = "AdminArea")]
    public class UserManagerController : Controller
    {
        private readonly IUnitOfWork _context;
        private readonly IMapper _mapper;
        private readonly UserManager<A_UserManager> _userManager;
        public UserManagerController(IUnitOfWork uow, IMapper mapper, UserManager<A_UserManager> userManager)
        {
            _context = uow;
            _mapper = mapper;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            var model = _context.UserManagerManagerUW.Get();
            return View(model);
        }
        [HttpGet]
        public IActionResult AddUser()
        {
            FillCombo();
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddUser(A_UserManagerViewModel model)
        {
            FillCombo();
            if (ModelState.IsValid)
            {
                //insert
                try
                {
                    
                    //کنترل تکراری نبودن نام کاربری
                    if (await _userManager.FindByNameAsync(model.UserName) != null)
                    {
                        ModelState.AddModelError("UserName", "نام کاربری تکراری می باشد.");
                        return View(model);
                    }
                  
                    var userMapped = _mapper.Map<A_UserManager>(model);
                    IdentityResult result = await _userManager.CreateAsync(userMapped, userMapped.Password);

                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                }
                catch
                {
                    //throw;
                    return RedirectToAction("ErrorView", "Home");
                }
            }
            return View(model);
        }
        [HttpGet]
        public IActionResult EditUser(String Id)
        {
            FillCombo();
            if (Id == null)
            {
                return RedirectToAction("ErrorView", "Home");
            }
            var proj = _context.UserManagerManagerUW.GetById(Id);
            var mapproj = _mapper.Map<A_UserManagerViewModel>(proj);
            return View(mapproj);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditUser(A_UserManagerViewModel model)
        {
            FillCombo();
            
            if (ModelState.IsValid)
            {
                var projmapper = _mapper.Map<A_UserManager>(model);
                _context.UserManagerManagerUW.Update(projmapper);
                _context.save();
                return RedirectToAction("Index");
            }
            return View(model);
        }
        [HttpGet]
        public IActionResult DeleteUser(string Id)
        {
            if (Id == null)
            {
                return RedirectToAction("ErrorView", "Home");
            }
            var proj = _context.UserManagerManagerUW.GetById(Id);
            if (proj == null)
            {
                return RedirectToAction("ErrorView", "Home");
            }
            return PartialView("_deleteUser", proj);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteUserPost(string Id)
        {
            if (Id == null)
            {
                return RedirectToAction("ErrorView", "Home");
            }
            _context.UserManagerManagerUW.DeleteById(Id);
            _context.save();
            return RedirectToAction("Index");

        }
        public void FillCombo()
        {
            List<P_Personel> ListPersonel = _context.PersonelUW.Get().ToList();
            ViewBag.personellist = ListPersonel;
        }
    }
}

DPEnergy/Areas/AdminArea/Views/AccessRight/AddRoleToUser.cshtml
@{
    ViewData["Title"] = "ثبت دسترسی ها";
}

    <div class="content">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="@Url.Action("Index","AccessRight")">مدیریت دسترسی</a></li>

                <li class="breadcrumb-item active" aria-current="page">اعظای حقوق دسترسی به کاربر</li>
            </ol>
        </nav>
        <div class="panel panel-heading" style="box-shadow:3px 1px 1px 0 gray; border-radius:2px;">
            <span style="font-weight:bold;">
                <i class="icon-accessibility"></i>
                ثبت دسترسی برای کاربر<span style="color:darkgreen">   @ViewBag.FullName</span>
            </span>
        </div>
        <div id="divmsg" style="text-align:center; font-weight:bold" class=""></div>
        <input name="userId" id="userId" class="hidden" value="@ViewBag.userId" />

        <div class="alert" style="border:1px solid gray; font-weight:bold; margin-top:15px;
                                text-align:center; font-size:15px; background-color:#d1cccc;">
            برای ثبت دسترسی یک یا چند دسترسی را تیک بزنید.
        </div>

        <div class="panel panel-body container-fluid overflow-auto" style="border-radius:2px; height:450px;
                    box-shadow:3px 1px 1px 0 gray; background-color:#e6e2e2;">
            <div id="jstreeAccessRight">

            </div>
        </div>
        @if (ViewBag.userRole != null)
        {
            <input id="rolelist" class="hidden" value="@ViewBag.userRole" />
        }

        <input id="SelectedItems" name="SelectedItems" type="text" class="hidden" />
        <input name="userId" id="userId" class="hidden" value="@ViewBag.userId" />

        <div class="col-xs-12 form-group" style="margin-top:15px;">
            <button id="btnsubmit" style="border:1px solid gray; border-radius:3px;"
                    class="btn pull-right">
                ثبت دسترسی
            </button>
        </div>
    </div>


@section AdminScripts{
    <script>
        $(function () {
            $("#jstreeAccessRight").on("changed.jstree", function (e, data) {

                var i, j;
                var postedItems = [];

                j = data.selected.length;
                for (var i = 0; i < j; i++) {
                    postedItems.push({
                        text: data.instance.get_node(data.selected[i]).text,
                        id: data.selected[i],
                        parent: data.node.parents[0]
                    });
                }
                
                $("#SelectedItems").val(JSON.stringify(postedItems));
            }).jstree({
                "core": {
                    "themes": {
                        "variant":"large"
                    },
                    "data":  @Html.Raw(ViewBag.AccessRight) ,
                },
                "checkbox": {
                    "Keep_selected_style":false
                },
                "plugins": ["checkbox"],
                //not all child nodes checked if parent is checked
                checkbox: { three_state: false, cascade: "" }
            }).on("loaded.jstree", function () {
                // all  node will be open on deafualt
                $.jstree.reference('#jstreeAccessRight').open_node("1");

                var urole = $("#rolelist").val().split(",");
                $("#jstreeAccessRight").jstree(true).select_node(urole);
            });
        });
    </script>
    <script>

    $("#btnsubmit").on('click', function (e) {
        e.preventDefault();

        if ($('#SelectedItems').val() == "" || $('#SelectedItems').val() == '[]') {
            alert('لطفا حداقل یک دسترسی را انتخاب نمایید');
            return false;
        }

        $.ajax({
            type: "Post",
            url: '@Url.Action("AddRoleToUser","AccessRight")',
            data: { 'selectedItems': $("#SelectedItems").val(), 'userId': $("#userId").val() },

        }).done(function (result) {
            if (result.status == 'noselected') {
                $("#divmsg").html('هیچ دسترسی انتخاب نشده است.');
                $("#divmsg").addClass('alert').addClass('alert-danger')
            }
            if (result.status == 'success') {
                 $("#divmsg").html('دسترسیها با موفقیت ثبت شد');
                $("#divmsg").addClass('alert').addClass('alert-success')
            }

        });
    });

    </script>
}

DPEnergy/Areas/AdminArea/Views/AccessRight/ErrorView.cshtml
@{
    ViewData["Title"] = "ErrorView";
}

<h2>ErrorView</h2>

DPEnergy/Areas/AdminArea/Views/AccessRight/Index.cshtml
@model IEnumerable<DPEnergy.DataModelLayer.ViewModels.Admin.NameAndPersonelCodeViewModel>
@using DPEnergy.CommonLayer.PublicClass
@{
    ViewData["Title"] = "Index";
}
<div class="content">

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">خانه</a></li>

            <li class="breadcrumb-item active" aria-current="page">مدیریت دسترسی</li>
        </ol>
    </nav>
    <div class="panel panel-heading" style="box-shadow:3px 1px 1px 0 gray; border-radius:2px;">
        <span style="font-weight:bold;">
            <i class="glyphicon glyphicon-list"></i>
           مدیریت دسترسی کاربران
        </span>
    </div>
    

    <div id="dummyScrollWrapper" style="overflow-x: scroll; margin-right:17px; margin-left:2px;">
        <div id="dummyScroll" style="height: 20px;">
        </div>
    </div>

    <div>
        <!--<div class="table-responsive"></div> -->
        <div class="k-rtl">
            <div id="grid"></div>
        </div>
    </div>

    <div class="modal fade" id="myModaldeletor">
        <div class="modal-dialog">
            <div class="modal-content">
                <form asp-controller="UserManager" asp-action="DeleteUserPost" method="post">
                    <div class="modal-header" style="background-color:darkred; color:white; border-radius:5px 5px 0 0;">
                        <h4 class="modal-title">Delete User</h4>
                    </div>

                    <div class="modal-body" id="DeleteModalBody">

                    </div>

                    <div dir="rtl" class="modal-footer" style="text-align:left;">
                        <button class="btn btn-default" type="button" style="width:80px;" data-dismiss="modal">Reject</button>
                        <button type="submit" class="btn" style="width:80px; color:white; background-color:darkred;">
                            Accept
                        </button>
                    </div>

                </form>

            </div>
        </div>
    </div>
</div>

@section AdminScripts{
    <script>
        $(document).ready(function () {
           var myobj = '@Html.Raw(Json.Serialize(Model))';
            var dpjson = JSON.parse(myobj);
            console.log(dpjson);

            $("#grid").kendoGrid({
                dataSource: {
                    data: dpjson,
                    pageSize: dpjson.length
                },
                height: 550,
                filterable: true,
                groupable: true,
                sortable: true,
                toolbar: ["pdf", "search"],

                pageable: {
                    refresh: true,
                    pageSizes: true,
                    buttonCount: 5
                },
                columns:
                [

                   {
                       field: "id",
                       width: "180px",
                       title: "User ID"
                   },{
                        field: "firstName",
                        width: "180px",
                        title: "FirstName"
                    }, {
                        field: "lastName",
                        width: "180px",
                        title: "LastName"
                    }, {
                        field: "personelCode",
                        width: "180px",
                        title: "PersonelCode"
                    }, {
                        field: "userName",
                        width: "200px",
                        title: "UserName"
                    },


                        {
                        width: "200px",
                        command:
                        {

                            name: "Access",
                            className: "customBlue1",
                            title: "مدیریت دسترسی",
                            click: function (e) {
                                // command button click handler
                                var dataItem = this.dataItem($(e.currentTarget).closest("tr"));
                               
                                var id = dataItem.id;
                                var firstname = dataItem.firstName;
                                var lastname = dataItem.lastName;
                                window.location.href = "/AdminArea/AccessRight/AddRoleToUser?id=" + id + "&firstname=" + firstname + "&lastname=" + lastname;
                                
                            },
                        },
                      
                    },
                    

                ]



            });
            var grid = $("#grid").data("kendoGrid");
            grid.hideColumn("id");

            //$("#grid").data("kendoGrid").wrapper.find(".k-grid-header-wrap").off("scroll.kendoGrid");

        });


    </script>
}