DPEnergy/Areas/DMSArea/Controllers/BasicInformation/ClientDiciplineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using DPEnergy.CommonLayer.PublicClass;
using DPEnergy.DataModelLayer.Entities;
using DPEnergy.DataModelLayer.Entities.Admin;
using DPEnergy.DataModelLayer.Entities.DMS.BasicInformation;
using DPEnergy.DataModelLayer.Services;
using DPEnergy.DataModelLayer.ViewModels;
using DPEnergy.DataModelLayer.ViewModels.DMS.BasicInformation;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace DPEnergy.Areas.DMSArea.Controllers.BasicInformation
{
    [Area("DMSArea")]
    [Authorize(Roles = "DMSArea")]
    public class ClientDiciplineController : Controller
    {
        private readonly IUnitOfWork _context;
        private readonly IMapper _mapper;
        private readonly UserManager<A_UserManager> _userManager;
        public ClientDiciplineController(IUnitOfWork uow, IMapper mapper, UserManager<A_UserManager> userManager)
        {
            _context = uow;
            _mapper = mapper;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            var model = _context.ClientDiciplineManagerUW.Get();
            return View(model);
        }
        [HttpGet]
        public IActionResult AddClientDicipline()
        {
            FillCombo();
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddClientDicipline(D_ClientDiciplineViewModel model)
        {
            FillCombo();
            if (ModelState.IsValid)
            {
                JsonHelper.SanitizeStringProperties(model);
                model.Creator = _context.UserManagerUW.GetById(_userManager.GetUserId(HttpContext.User)).ToString();
                model.CreationDate = DateTime.Now;
                _context.ClientDiciplineManagerUW.Create(_mapper.Map<D_ClientDicipline>(model));
                _context.save();

                return RedirectToAction("Index");
            }
            return View(model);
        }
        [HttpGet]
        public IActionResult EditClientDicipline(String Id)
        {
            FillCombo();
            if (Id == null)
            {
                var errorMessage = "No id found for the selected row.";
                return View("~/Views/Shared/Error.cshtml", errorMessage);
            }
            var proj = _context.ClientDiciplineManagerUW.GetById(Id);
            var mapproj = _mapper.Map<D_ClientDiciplineViewModel>(proj);
            return View(mapproj);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditClientDicipline(D_ClientDiciplineViewModel model )
        {
            FillCombo();
            model.ModificationDate = DateTime.Now;
            model.Modifier = _context.UserManagerUW.GetById(_userManager.GetUserId(HttpContext.User)).ToString();
            if (ModelState.IsValid)
            {
                JsonHelper.SanitizeStringProperties(model);
                var projmapper = _mapper.Map<D_ClientDicipline>(model);
                _context.ClientDiciplineManagerUW.Update(projmapper);
                _context.save();
                return RedirectToAction("Index");
            }
            return View(model);
        }
        [HttpGet]
        public IActionResult DeleteClientDicipline(string Id)
        {
            if (Id == null)
            {
                var errorMessage = "No id found for the selected row.";
                return View("~/Views/Shared/Error.cshtml", errorMessage);
            }
            var proj = _context.ClientDiciplineManagerUW.GetById(Id);
            if (proj == null)
            {
                var errorMessage = "No data found for the selected row id.";
                return View("~/Views/Shared/Error.cshtml", errorMessage);
            }
            return PartialView("_deleteClientDicipline", proj);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteClientDiciplinePost(string Id)
        {
            if (Id == null)
            {
                var errorMessage = "No id found for the selected row.";
                return View("~/Views/Shared/Error.cshtml", errorMessage);
            }
            _context.ClientDiciplineManagerUW.DeleteById(Id);
            _context.save();
            return RedirectToAction("Index");

        }
        public void FillCombo()
        {
            List<D_Project> ListProject = _context.projectManagerUW.Get().ToList();
            ViewBag.projectlist = ListProject;
            
        }
    }
}

DPEnergy/Areas/DMSArea/Views/ClientDicipline/AddClientDicipline.cshtml
@model DPEnergy.DataModelLayer.ViewModels.DMS.BasicInformation.D_ClientDiciplineViewModel
@using DPEnergy.CommonLayer.PublicClass
@{
    ViewData["Title"] = "AddClientDicipline";
    List<D_Project> ListProject = ViewBag.projectlist;
    
}
<div class="content">

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">Home</a></li>
            <li class="breadcrumb-item"><a href="#">Basic Information</a></li>
            <li class="breadcrumb-item"><a href=" @Url.Action("Index", "ClientDicipline") ">ClientDicipline</a></li>
            <li class="breadcrumb-item active" aria-current="page">Add ClientDicipline</li>
        </ol>
    </nav>
    <div class="panel panel-heading" style="box-shadow:3px 1px 1px 0 gray; border-radius:2px;">
        <span style="font-weight:bold;">
            <i class="glyphicon glyphicon-list"></i>
            Add  ClientDicipline
        </span>
    </div>


    <div class="panel panel-body container-fluid" style="border-radius:2px; box-shadow:3px 1px 1px 0 gray; background-color:#dae7f4;">
        <form asp-controller="ClientDicipline" asp-action="AddClientDicipline" method="post" enctype="multipart/form-data">

            <div class="col-md-6 col-md-offset-3">

                <!--ProjectCode-->
                <div>
                    <label asp-for="ProjectCode" class="control-label col-md-3 col-xs-12"></label>
                    <div class="col-md-9 col-xs-12">
                        <select asp-for="ProjectCode" asp-items="@(new SelectList(ListProject,"ProjectCode","ProjectCode"))" class="form-control selectpicker custominput" id="select-ProjectCode" data-live-search="true" style="direction: ltr">
                            <option value="" selected disabled hidden style="direction: ltr">Select Project Code</option>
                        </select>
                        <span asp-validation-for="ProjectCode" class="text-danger"></span>
                        <div>   </div>
                    </div>

                </div>
                <!--Dicipline-->
                <div>
                    <label asp-for="Dicipline" class="control-label col-md-3 col-xs-12"></label>
                    <div class="col-md-9 col-xs-12">
                        <input asp-for="Dicipline" type="text" class="form-control custominput" placeholder="ClientDicipline ..." autocomplete="off" />
                        <span asp-validation-for="Dicipline" class="text-danger"></span>
                    </div>

                </div>
                <!--Title-->
                <div>
                    <label asp-for="Title" class="control-label col-md-3 col-xs-12"></label>
                    <div class="col-md-9 col-xs-12">
                        <input asp-for="Title" type="text" class="form-control custominput" placeholder="Title ..." autocomplete="off" />
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                </div>
                <!--Order-->
                <div>
                    <label asp-for="Order" class="control-label col-md-3 col-xs-12"></label>
                    <div class="col-md-9 col-xs-12">
                        <input asp-for="Order" type="text" class="form-control custominput" placeholder="Order ..." autocomplete="off" />
                        <span asp-validation-for="Order" class="text-danger"></span>
                    </div>

                </div>

                <div class="col-xs-12 form-group" style="margin-top:15px;">
                    <input type="submit" style="border:1px solid gray; border-radius:3px;"
                           value="Submit" class="btn pull-right" />
                </div>

            </div>



        </form>
    </div>
</div>

DPEnergy/Areas/DMSArea/Views/ClientDicipline/EditClientDicipline.cshtml
@model DPEnergy.DataModelLayer.ViewModels.DMS.BasicInformation.D_ClientDiciplineViewModel
@using DPEnergy.CommonLayer.PublicClass
@{
    ViewData["Title"] = "EditClientDicipline";
    List<D_Project> ListProject = ViewBag.projectlist;
   
}
<div class="content">

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">Home</a></li>
            <li class="breadcrumb-item"><a href="#">Basic Information</a></li>
            <li class="breadcrumb-item"><a href=" @Url.Action("Index", "ClientDicipline") ">ClientDicipline</a></li>
            <li class="breadcrumb-item active" aria-current="page">Edit ClientDicipline</li>
        </ol>
    </nav>
    <div class="panel panel-heading" style="box-shadow:3px 1px 1px 0 gray; border-radius:2px;">
        <span style="font-weight:bold;">
            <i class="glyphicon glyphicon-list"></i>
            Edit  ClientDicipline
        </span>
    </div>


    <div class="panel panel-body container-fluid" style="border-radius:2px; box-shadow:3px 1px 1px 0 gray; background-color:#dae7f4;">
        <form asp-controller="ClientDicipline" asp-action="EditClientDicipline" method="post" enctype="multipart/form-data">

            <div class="col-md-6 col-md-offset-3">

                <!--ProjectCode-->
                <div>
                    <label asp-for="ProjectCode" class="control-label col-md-3 col-xs-12"></label>
                    <div class="col-md-9 col-xs-12">
                        <select asp-for="ProjectCode" asp-items="@(new SelectList(ListProject,"ProjectCode","ProjectCode"))" class="form-control selectpicker custominput" id="select-ProjectCode" data-live-search="true" style="direction: ltr">
                            <option value="" selected disabled hidden style="direction: ltr">Select Project Code</option>
                        </select>
                        <span asp-validation-for="ProjectCode" class="text-danger"></span>
                        <div>   </div>
                    </div>

                </div>
                <!--Dicipline-->
                <div>
                    <label asp-for="Dicipline" class="control-label col-md-3 col-xs-12"></label>
                    <div class="col-md-9 col-xs-12">
                        <input asp-for="Dicipline" type="text" class="form-control custominput" placeholder="ClientDicipline ..." autocomplete="off" />
                        <span asp-validation-for="Dicipline" class="text-danger"></span>
                    </div>

                </div>
                <!--Title-->
                <div>
                    <label asp-for="Title" class="control-label col-md-3 col-xs-12"></label>
                    <div class="col-md-9 col-xs-12">
                        <input asp-for="Title" type="text" class="form-control custominput" placeholder="Title ..." autocomplete="off" />
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>

                </div>
                <!--Order-->
                <div>
                    <label asp-for="Order" class="control-label col-md-3 col-xs-12"></label>
                    <div class="col-md-9 col-xs-12">
                        <input asp-for="Order" type="text" class="form-control custominput" placeholder="Order ..." autocomplete="off" />
                        <span asp-validation-for="Order" class="text-danger"></span>
                    </div>

                </div>
                <!--Creation Date -->
                <input asp-for="CreationDate" type="hidden" class="form-control custominput" />
                <!--Creator-->
                <input asp-for="Creator" type="hidden" class="form-control custominput" />

                <!--ModificationDate -->
                <input asp-for="ModificationDate" type="hidden" class="form-control custominput" />
                <!--Modifier-->
                <input asp-for="Modifier" type="hidden" class="form-control custominput" />
             

                <div class="col-xs-12 form-group" style="margin-top:15px;">
                    <input type="submit" style="border:1px solid gray; border-radius:3px;"
                           value="Submit" class="btn pull-right" />
                </div>

            </div>



        </form>
    </div>
</div>

DPEnergy/Areas/DMSArea/Views/ClientDicipline/Index.cshtml
@model IEnumerable<DPEnergy.DataModelLayer.Entities.DMS.BasicInformation.D_ClientDicipline>
@using DPEnergy.CommonLayer.PublicClass
@{
    ViewData["Title"] = "Index";
}
<div class="content">

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">Home</a></li>
            <li class="breadcrumb-item"><a href="#">Basic Information</a></li>
            <li class="breadcrumb-item active" aria-current="page">ClientDicipline</li>
        </ol>
    </nav>
    <div class="panel panel-heading" style="box-shadow:3px 1px 1px 0 gray; border-radius:2px;">
        <span style="font-weight:bold;">
            <i class="glyphicon glyphicon-list"></i>
            ClientDicipline List
        </span>
    </div>
    <div style="margin-bottom:5px;">
        <a class="btn customGreen1" asp-controller="ClientDicipline" asp-action="AddClientDicipline">
            <i class="glyphicon glyphicon-plus"></i>
            Add ClientDicipline
        </a>
    </div>


    <div>
        <div id="grid"></div>
        <ul id="context-menu">
            <li id="DeleteContext">Delete</li>
            <li id="EditContext"> Edit</li>
        </ul>
    </div>
</div>
<div class="modal fade" id="myModaldeletor">
    <div class="modal-dialog">
        <div class="modal-content">
            <form asp-controller="ClientDicipline" asp-action="DeleteClientDiciplinePost" method="post">
                <div class="modal-header" style="background-color:darkred; color:white; border-radius:5px 5px 0 0;">
                    <h4 class="modal-title">Delete ClientDicipline</h4>
                </div>

                <div class="modal-body" id="DeleteModalBody">

                </div>

                <div dir="rtl" class="modal-footer" style="text-align:left;">
                    <button class="btn btn-default" type="button" style="width:80px;" data-dismiss="modal">Reject</button>
                    <button type="submit" class="btn" style="width:80px; color:white; background-color:darkred;">
                        Accept
                    </button>
                </div>

            </form>

        </div>
    </div>
</div>

@section DMSScripts{
    <script>
        $(document).ready(function () {
           var myobj = '@Html.Raw(Json.Serialize(Model))';
            var dpjson = JSON.parse(myobj);
            console.log(dpjson);

            $("#grid").kendoGrid({
                dataSource: {
                    data: dpjson,
                    pageSize: dpjson.length
                },
                height: 550,
                filterable: true,
                groupable: true,
                sortable: true,
                toolbar: ["pdf", "search","excel"],

                pageable: {
                    refresh: true,
                    pageSizes: true,
                    buttonCount: 5
                },
                columns: [{
                    field: "id",
                    title: "id"
                }, {
                   field: "projectCode",
                   filterable: {
                            multi: true
                        },
                   width: 150,
                    title: "ProjectCode"
                }, {
                    field: "dicipline",
                    width: 150,
                    title: "Dicipline"
                }, {
                    field: "title",
                     width: 200,
                     title: "Title"
                }, {
                        field: "order",
                        width: 150,
                     title: "Order"
                }, {

                        field: "creator",
                        width: 150,
                      title: "Creator"
                }, {
                        field: "creationDate",
                        width: 200,
                     title: "Creation Date"
                }, {
                        field: "modifier",
                        width: 150,
                     title: "Modifier"
                }, {
                        field: "modificationDate",
                        width: 200,
                     title: "Modification Date"
                },




                    {
                        width: 150,
                        command: [

                            {
                                name: "del",
                                text: "Delete",
                                click: function (e) {
                                    // command button click handler
                                    var item = this.dataItem($(e.currentTarget).closest("tr"));
                                    url = "/DMSArea/ClientDicipline/DeleteClientDicipline";
                                    $.ajax({
                                        url: url,
                                        data: { id: item.id },
                                        type: 'Get',
                                        success: function (result) {
                                            $('#DeleteModalBody').html(result);
                                            $("#myModaldeletor").modal("show");
                                        },
                                        error: function (xhr, status) {
                                            alert(status);
                                        }
                                    });
                                }
                            },
                            {
                                name: "edit",
                                text: "Edit",
                                click: function (e) {
                                    // command button click handler
                                    var item = this.dataItem($(e.currentTarget).closest("tr"));
                                    console.log(item )
                                    window.location.href = '@Url.Action("EditClientDicipline", "ClientDicipline")/' + item.id;
                                }
                            },

                        ]
                    }
                ]

            });
            var grid = $("#grid").data("kendoGrid");
            grid.hideColumn("id");

            //$("#grid").data("kendoGrid").wrapper.find(".k-grid-header-wrap").off("scroll.kendoGrid");

        });

            $("#context-menu").kendoContextMenu({
                target: "#grid",
                filter: "tr[role='row']",
                select: function (e) {
                    var grid = $("#grid").data("kendoGrid");
                    var model = grid.dataItem(e.target);
                    var item = e.item.id;
                    console.log(item);
                   // console.log(e.target);
                    switch (item) {
                        case "EditContext":
                            window.location.href = '@Url.Action("EditClientDicipline", "ClientDicipline")/' + model.id;
                            break;
                        case "DeleteContext":
                            url = "/DMSArea/ClientDicipline/DeleteClientDicipline";
                            console.log("here");
                            $.ajax({
                                url: url,
                                data: { id: model.id },
                                type: 'Get',
                                success: function (result) {

                                        $('#DeleteModalBody').html(result);
                                        $("#myModaldeletor").modal("show");

                                },
                                error: function (xhr, status) {
                                    alert(status);
                                }
                            });
                            break;

                    };
                }
            });
    </script>
}

DPEnergy/Areas/DMSArea/Views/ClientDicipline/_deleteClientDicipline.cshtml
@model DPEnergy.DataModelLayer.Entities.DMS.BasicInformation.D_ClientDicipline
@{
    Layout = null;
}

<div class="modal-body form-horizontal">
    Are you sure you want to delete Client Dicipline
    <span style="font-weight:bold;">@Model.Dicipline<span>
    ?
</div>
<input type="hidden" asp-for="Id" />