DPEnergy/Areas/PersonelArea/Controllers/LetterRequestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using DPEnergy.CommonLayer.PublicClass;
using DPEnergy.CommonLayer.Services;
using DPEnergy.DataModelLayer;
using DPEnergy.DataModelLayer.Entities;
using DPEnergy.DataModelLayer.Entities.Admin;
using DPEnergy.DataModelLayer.Entities.Personel;
using DPEnergy.DataModelLayer.Services;
using DPEnergy.DataModelLayer.ViewModels.Personel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace DPEnergy.Areas.PersonelArea.Controllers
{

    
    [Area("PersonelArea")]
    [Authorize(Roles = "PersonelArea")]
    public class LetterRequestController : Controller
        {
            private readonly IMapper _mapper;
            private readonly IUnitOfWork _context;
            private readonly DataModelLayer.ApplicationDbContext _dbcontext;
            private readonly UserManager<A_UserManager> _userManager;
            private readonly IUploadFiles _upload;
            public LetterRequestController(IUnitOfWork uow, IMapper mapper, UserManager<A_UserManager> userManager, IUploadFiles upload, ApplicationDbContext dbcontext)
            {
                _dbcontext = dbcontext;
                _userManager = userManager;
                _context = uow;
                _mapper = mapper;
                _upload = upload;
            }
            public IActionResult Index()
            {

                var model = _context.LetterRequestUW.Get();
                return View(model);
            }
            [HttpGet]
            public IActionResult AddLetterRequest()
            {
                FillCombo();
                return View();
            }
            public int FindCounter(string personelCode)
            {
                var LetterRequest = _dbcontext.P_LetterRequest.Where(e => e.PersonelCode == personelCode);
                if (LetterRequest.Any())
                {
                    var maxCounter = LetterRequest.Max(e => e.Counter);
                    return maxCounter + 1;
                }
                return 1;
            }


            public IActionResult UploadAttachment(IEnumerable<IFormFile> filearray, string path, string personelcode, string extension)
            {
                var filename = personelcode + "-" + FindCounter(personelcode) + "." + extension;
                var result = _upload.UploadAttachmentByPersonelCode(filearray, path, personelcode, filename);
                if (result == "duplicate")
                {
                    return Json(new { status = "duplicate" });
                }

                return Json(new { status = "success", mypath = result.Replace("\\", "/"), filename = filename });

            }
        public IActionResult UploadAttachmentEdit(IEnumerable<IFormFile> filearray, string path, string personelcode, string extension , string id)
        {
            var counter = _dbcontext.P_LetterRequest.First(x => x.Id == id).Counter;
 
            var filename = personelcode + "-" + counter + "." + extension;
            var result = _upload.UploadAttachmentByPersonelCode(filearray, path, personelcode, filename);
            if (result == "duplicate")
            {
                return Json(new { status = "duplicate" });
            }

            return Json(new { status = "success", mypath = result.Replace("\\", "/"), filename = filename });

        }
        public IActionResult DeleteAttachment(string path, string id)
            {
                if (path == null)
                {
                    return Json(new { status = "nofile" });
                }
                if (id != null)
                {
                    var record = _dbcontext.P_LetterRequest.First(x => x.Id == id);
                    if (!string.IsNullOrEmpty(record.Attachment))
                    {
                        record.Attachment = null;
                        _context.LetterRequestUW.Update(record);
                        _context.save();
                    }
                }
             var result = _upload.DeleteAttachmentByPersonelCode(path, "", "");
            if (result == false)
                {
                    return Json(new { status = "nofile" });
                }

                return Json(new { status = "success" });

            }
            [HttpPost]
            [ValidateAntiForgeryToken]
            public IActionResult AddLetterRequest(P_LetterRequestViewModel model, string issuedatee, string expiredatee)
            {
                FillCombo();
                model.CreationDate = DateTime.Now;
                model.Creator = _context.UserManagerUW.GetById(_userManager.GetUserId(HttpContext.User)).ToString();
                model.Counter = FindCounter(model.PersonelCode);
                if (ModelState.IsValid)
                {
                    if (issuedatee != null)
                    {
                        model.IssueDate = ConvertDateTime.ConvertShamsiToMiladi(issuedatee);
                    }
                    if (expiredatee != null)
                    {
                        model.ExpirationDate = ConvertDateTime.ConvertShamsiToMiladi(expiredatee);
                    }

                    _context.LetterRequestUW.Create(_mapper.Map<P_LetterRequest>(model));
                    _context.save();

                    return RedirectToAction("Index");
                }
                return View(model);
            }
            [HttpGet]
            public IActionResult EditLetterRequest(String Id)
            {
                FillCombo();
                if (Id == null)
                {
                    var errorMessage = "No id found for selected row.";
                    return View("~/Views/Shared/Error.cshtml", errorMessage);
                }
                var comp = _context.LetterRequestUW.GetById(Id);
                var mapcomp = _mapper.Map<P_LetterRequestViewModel>(comp);
                return View(mapcomp);

            }
            [HttpPost]
            [ValidateAntiForgeryToken]
            public IActionResult EditLetterRequest(P_LetterRequestViewModel model, string issuedatee, string expiredatee)
            {
                FillCombo();
                model.ModificationDate = DateTime.Now;
                model.Modifier = _context.UserManagerUW.GetById(_userManager.GetUserId(HttpContext.User)).ToString();
                if (ModelState.IsValid)
                {
                if (issuedatee != null)
                {
                    model.IssueDate = ConvertDateTime.ConvertShamsiToMiladi(issuedatee);
                }
                if (expiredatee != null)
                {
                    model.ExpirationDate = ConvertDateTime.ConvertShamsiToMiladi(expiredatee);
                }
                var compmapper = _mapper.Map<P_LetterRequest>(model);
                    _context.LetterRequestUW.Update(compmapper);
                    _context.save();
                    return RedirectToAction("Index");
                }
                return View(model);
            }
            [HttpGet]
            public IActionResult DeleteLetterRequest(string Id)
            {
                if (Id == null)
                {
                    return RedirectToAction("ErrorView", "Home");
                }
                var city = _context.LetterRequestUW.GetById(Id);
                if (city == null)
                {
                    return RedirectToAction("ErrorView", "Home");
                }
                return PartialView("_deleteLetterRequest", city);
            }
            [HttpPost]
            [ValidateAntiForgeryToken]
            public IActionResult DeleteLetterRequestPost(string Id)
            {
                if (Id == null)
                {
                    return RedirectToAction("ErrorView", "Home");
                }
                var model = _context.LetterRequestUW.GetById(Id);
                DeleteAttachment(model.Attachment, null);
                _context.LetterRequestUW.DeleteById(Id);
                _context.save();
                return RedirectToAction("Index");

            }
            public IActionResult GetName(string personelcode)
            {
                var data = _context.PersonelUW.Get(x => x.PersonelCode == personelcode).ToList()[0];
                var Jsondata = new
                {

                    Lastname = data.LastName,
                    Firstname = data.FirstName,

                };

                return Json(Jsondata);

            }
            public void FillCombo()
            {

                List<P_Personel> ListPersonel = _context.PersonelUW.Get().ToList();
                ViewBag.personellist = ListPersonel;
            }
        }
    }

DPEnergy/Areas/PersonelArea/Views/LetterRequest/Index.cshtml
@model IEnumerable<DPEnergy.DataModelLayer.Entities.Personel.P_LetterRequest>
@using DPEnergy.CommonLayer.PublicClass
@{
    ViewData["Title"] = "Index";
}


<div class="content">

    <ul class="breadcrumb">
        <li><a asp-controller="Home" asp-action="index"><i class="icon-home2 position-left"></i> صفحه اصلی</a></li>
        <li><a href="#"><i class="position-left"></i> مشخصات پرسنل</a></li>
        <li class="active">درخواست نامه</li>
    </ul>
    <div class="panel panel-heading" style="box-shadow:3px 1px 1px 0 gray; border-radius:2px;">
        <span style="font-weight:bold;">
            <i class="glyphicon glyphicon-list"></i>
            لیست درخواست ها
        </span>
    </div>
    <div style="margin-bottom:5px;">
        <a class="btn customGreen1" asp-controller="LetterRequest" asp-action="AddLetterRequest">
            <i class="glyphicon glyphicon-plus"></i>
            افزودن درخواست نامه 
        </a>
    </div>

    <div>
        <!--<div class="table-responsive"></div> -->
        <div class="k-rtl">
            <div id="grid"></div>
        </div>
    </div>

</div>

<div class="modal fade" id="myModaldeletor">
    <div class="modal-dialog">
        <div class="modal-content">
            <form asp-controller="LetterRequest" asp-action="DeleteLetterRequestPost" method="post">
                <div class="modal-header" style="background-color:darkred; color:white; border-radius:5px 5px 0 0;" dir="rtl">
                    <h4 class="modal-title">حذف درخواست نامه</h4>
                </div>

                <div class="modal-body" id="DeleteModalBody">

                </div>

                <div dir="rtl" class="modal-footer" style="text-align:left;">
                    <button class="btn btn-default" type="button" style="width:80px;" data-dismiss="modal">بازگشت</button>
                    <button type="submit" class="btn" style="width:80px; color:white; background-color:darkred;">
                        تایید
                    </button>
                </div>

            </form>

        </div>
    </div>
</div>
@Html.Partial("_Modal", new BootstrapModel { ID = "modal-action", Size = BootstrapModel.ModalSize.Large })
@section PersonelScripts {
    <script src="~/js/modal/modal.js"></script>
    <script>

        $(document).ready(function () {
           var myobj = '@Html.Raw(Json.Serialize(Model))';
            var dpjson = JSON.parse(myobj);
            console.log(dpjson)
            $("#grid").kendoGrid({
                dataSource: {
                    data: dpjson,
                    pageSize: dpjson.length,
                     schema: {
                        model: {
                            fields: {

                                creationDate: { type: "date" },
                                modificationDate: { type: "date" },

                            }
                        }
                    }
                },
                height: 550,
                filterable: true,
                groupable: true,
                sortable: true,
                toolbar: ["pdf", "search"],

                pageable: {
                    refresh: true,
                    pageSizes: true,
                    buttonCount: 5
                },
                columns: [
                {
                        field: "id",
                        width: 150,
                        title: "id"
                },{
                    filterable: {
                        multi: true
                    },
                    field: "personelCode",
                    width: 150,
                    title: "کد پرسنلی"
                }, {
                    field: "firstName",
                     width: 150,
                    title: "نام "
                }, {
                    field: "lastName",
                    width: 150,
                    title: "نام خانوادگی"
                }, {
                    field: "subject",
                    width: 150,
                    title: "عنوان نامه "
                }, {
                    field: "reciever",
                    width: 150,
                    title: "گیرنده"
                }, {
                    field: "issueDate",
                    width: 150,
                    title: "تاریخ صدور"
                }, {
                    field: "expirationDate",
                    width: 150,
                    title: "تاریخ انقضا"
                },  {
                    field: "creator",
                    width: 150,
                    title: "ایجاد کننده"
                }, {
                    field: "creationDate",
                    width: 150,
                    attributes: {
                        style: "text-align: left;"
                    },
                    format: "{0:yyyy-MM-dd}",
                    template: "#= kendo.toString(creationDate, 'yyyy-MM-dd') #" ,

                    title: "تاریخ ایجاد"
                }, {
                    field: "modifier",
                    width: 150,
                    title: "اصلاح کننده"
                }, {
                    field: "modificationDate",
                    format: "{0:yyyy-MM-dd}",
                    template: "#= kendo.toString(modificationDate, 'yyyy-MM-dd') #",
                    width: 200,
                    title: "تاریخ اصلاح"
                },

                    {
                        width: 150,
                        command: [
                            {

                                name: "del",
                                text: "حذف",
                                click: function (e) {
                                    var item = this.dataItem($(e.currentTarget).closest("tr"));
                                    url = "/PersonelArea/LetterRequest/DeleteLetterRequest";
                                    $.ajax({
                                        url: url,
                                        data: { id  : item.id },
                                        type: 'Get',
                                        success: function (result) {
                                            $('#DeleteModalBody').html(result);
                                            $("#myModaldeletor").modal("show");
                                        },
                                        error: function (xhr, status) {
                                            alert(status);
                                        }
                                    });
                                }
                            },

                            {

                                name: "edit",
                                text: "ویرایش",
                                click: function (e) {

                                    var item = this.dataItem($(e.currentTarget).closest("tr"));
                                    window.location.href = '@Url.Action("EditLetterRequest", "LetterRequest")/' + item.id;
                                }
                            },

                        ]
                    }
                ]

            });
            var grid = $("#grid").data("kendoGrid");
            grid.hideColumn("id");
        });


    </script>

}

DPEnergy/Areas/PersonelArea/Views/LetterRequest/_deleteLetterRequest.cshtml
@model DPEnergy.DataModelLayer.Entities.Personel.P_LetterRequest
@{
    Layout = null;
}

<div class="modal-body form-horizontal" dir="rtl">
    از حذف درخواست نامه پرسنل
    <span style="font-weight:bold;">@Model.FirstName @Model.LastName</span>
    با عنوان
    <span style="font-weight:bold;">@Model.Subject</span>
    مطمئن هستید؟
</div>
<input type="hidden" asp-for="Id" />