DPEnergy/Areas/DMSArea/Controllers/BasicInformation/ProjectTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using DPEnergy.CommonLayer.PublicClass;
using DPEnergy.DataModelLayer.Entities.DMS.BasicInformation;
using DPEnergy.DataModelLayer.Services;
using DPEnergy.DataModelLayer.ViewModels.DMS.BasicInformation;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DPEnergy.Areas.DMSArea.Controllers.BasicInformation
{
    [Area("DMSArea")]
    [Authorize(Roles = "DMSArea")]
    public class ProjectTypeController : Controller
    {
        private readonly IUnitOfWork _context;
        private readonly IMapper _mapper;
        public ProjectTypeController(IUnitOfWork uow, IMapper mapper)
        {
            _context = uow;
            _mapper = mapper;
        }
        public IActionResult Index()
        {
            var model = _context.ProjectTypeManagerUW.Get();
            return View(model);
        }
        [HttpGet]
        public IActionResult AddProjectType()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddProjectType(D_ProjectTypeViewModel model)
        {
            if (ModelState.IsValid)
            {
                JsonHelper.SanitizeStringProperties(model);
                _context.ProjectTypeManagerUW.Create(_mapper.Map<D_ProjectType>(model));
                _context.save();

                return RedirectToAction("Index");
            }
            return View(model);
        }
        [HttpGet]
        public IActionResult EditProjectType(String Id)
        {
            if (Id == null)
            {
                var errorMessage = "No id found for the selected row.";
                return View("~/Views/Shared/Error.cshtml", errorMessage);
            }
            var proj = _context.ProjectTypeManagerUW.GetById(Id);
            var mapproj = _mapper.Map<D_ProjectTypeViewModel>(proj);
            return View(mapproj);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditProjectType(D_ProjectTypeViewModel model)
        {
            if (ModelState.IsValid)
            {
                JsonHelper.SanitizeStringProperties(model);
                var projmapper = _mapper.Map<D_ProjectType>(model);
                _context.ProjectTypeManagerUW.Update(projmapper);
                _context.save();
                return RedirectToAction("Index");
            }
            return View(model);
        }
        [HttpGet]
        public IActionResult DeleteProjectType(string Id)
        {
            if (Id == null)
            {
                var errorMessage = "No id found for the selected row.";
                return View("~/Views/Shared/Error.cshtml", errorMessage);
            }
            var proj = _context.ProjectTypeManagerUW.GetById(Id);
            if (proj == null)
            {
                var errorMessage = "No data found for the selected row id.";
                return View("~/Views/Shared/Error.cshtml", errorMessage);
            }
            return PartialView("_deleteProjectType", proj);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteProjectTypePost(string Id)
        {
            if (Id == null)
            {
                return RedirectToAction("ErrorView", "Home");
            }
            _context.ProjectTypeManagerUW.DeleteById(Id);
            _context.save();
            return RedirectToAction("Index");

        }
    }
}

DPEnergy/Areas/DMSArea/Views/ProjectType/AddProjectType.cshtml
@model DPEnergy.DataModelLayer.ViewModels.DMS.BasicInformation.D_ProjectTypeViewModel

@{
    ViewData["Title"] = "AddProjectType";
}
<div class="content">

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">Home</a></li>
            <li class="breadcrumb-item"><a href="#">Basic Information</a></li>
            <li class="breadcrumb-item"><a href=" @Url.Action("Index", "ProjectType") ">Project Type</a></li>
            <li class="breadcrumb-item active" aria-current="page">Add Project Type</li>
        </ol>
    </nav>
    <div class="panel panel-heading" style="box-shadow:3px 1px 1px 0 gray; border-radius:2px;">
        <span style="font-weight:bold;">
            <i class="glyphicon glyphicon-list"></i>
            Add New Project Type
        </span>
    </div>


    <div class="panel panel-body container-fluid" style="border-radius:2px; box-shadow:3px 1px 1px 0 gray; background-color:#dae7f4;">
        <form asp-controller="ProjectType" asp-action="AddProjectType" method="post" enctype="multipart/form-data">
            <div class="col-md-6 col-md-offset-3">
                <!--ProjectType-->
                <div>
                    <label asp-for="ProjectType" class="control-label col-md-3 col-xs-12"></label>
                    <div class="col-md-9 col-xs-12">
                        <input asp-for="ProjectType" type="text" class="form-control custominput" placeholder="Project Type..." autocomplete="off" />
                        <span asp-validation-for="ProjectType" class="text-danger"></span>
                    </div>
                </div>
                <!--ProjectTypePersian-->
                <div>
                    <label asp-for="ProjectTypePersian" class="control-label col-md-3 col-xs-12"></label>
                    <div class="col-md-9 col-xs-12">
                        <input asp-for="ProjectTypePersian" type="text" class="form-control custominput" placeholder="Project Type..." autocomplete="off" />
                        <span asp-validation-for="ProjectTypePersian" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-xs-12 form-group" style="margin-top:15px;">
                    <input type="submit" style="border:1px solid gray; border-radius:3px;"
                           value="Submit" class="btn pull-right" />
                </div>
            </div>
            

        </form>
    </div>
</div>

DPEnergy/Areas/DMSArea/Views/ProjectType/EditProjectType.cshtml
@model DPEnergy.DataModelLayer.ViewModels.DMS.BasicInformation.D_ProjectTypeViewModel
@{
    ViewData["Title"] = "EditProjectType";
}
<div class="content">

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">Home</a></li>
            <li class="breadcrumb-item"><a href="#">Basic Information</a></li>
            <li class="breadcrumb-item"><a href=" @Url.Action("Index", "ProjectType") ">Project Type</a></li>
            <li class="breadcrumb-item active" aria-current="page">" Edit Project Type"</li>
        </ol>
    </nav>
    <div class="panel panel-heading" style="box-shadow:3px 1px 1px 0 gray; border-radius:2px;">
        <span style="font-weight:bold;">
            <i class="glyphicon glyphicon-list"></i>
            Add New Project Type
        </span>
    </div>


    <div class="panel panel-body container-fluid" style="border-radius:2px; box-shadow:3px 1px 1px 0 gray; background-color:#dae7f4;">
        <form asp-controller="ProjectType" asp-action="EditProjectType" method="post" enctype="multipart/form-data">
            <div class="col-md-6 col-md-offset-3">
                <!--ProjectType-->
                <div>
                    <label asp-for="ProjectType" class="control-label col-md-3 col-xs-12"></label>
                    <div class="col-md-9 col-xs-12">
                        <input asp-for="ProjectType" type="text" class="form-control custominput" placeholder="Project Type..." autocomplete="off" />
                        <span asp-validation-for="ProjectType" class="text-danger"></span>
                    </div>
                </div>
                <!--ProjectTypePersian-->
                <div>
                    <label asp-for="ProjectTypePersian" class="control-label col-md-3 col-xs-12"></label>
                    <div class="col-md-9 col-xs-12">
                        <input asp-for="ProjectTypePersian" type="text" class="form-control custominput" placeholder="Project Type..." autocomplete="off" />
                        <span asp-validation-for="ProjectTypePersian" class="text-danger"></span>
                    </div>
                </div>

                <div class="col-xs-12 form-group" style="margin-top:15px;">
                    <input type="submit" style="border:1px solid gray; border-radius:3px;"
                           value="Submit" class="btn pull-right" />
                </div>
            </div>


        </form>
    </div>
</div>

DPEnergy/Areas/DMSArea/Views/ProjectType/Index.cshtml
@model IEnumerable<DPEnergy.DataModelLayer.Entities.DMS.BasicInformation.D_ProjectType>
@using DPEnergy.CommonLayer.PublicClass
@{
    ViewData["Title"] = "Index";
}
    <div class="content">

        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">Home</a></li>
                <li class="breadcrumb-item"><a href="#">Basic Information</a></li>
                <li class="breadcrumb-item active" aria-current="page">Project Type</li>
            </ol>
        </nav>
        <div class="panel panel-heading" style="box-shadow:3px 1px 1px 0 gray; border-radius:2px;">
            <span style="font-weight:bold;">
                <i class="glyphicon glyphicon-list"></i>
                Project Type List
            </span>
        </div>
        <div style="margin-bottom:5px;">
            <a class="btn customGreen1" asp-controller="ProjectType" asp-action="AddProjectType">
                <i class="glyphicon glyphicon-plus"></i>
                Add New Project Type
            </a>
        </div>


        <div>
            <div id="grid"></div>
        </div>
    </div>
    <div class="modal fade" id="myModaldeletor">
        <div class="modal-dialog">
            <div class="modal-content">
                <form asp-controller="ProjectType" asp-action="DeleteProjectTypePost" method="post">
                    <div class="modal-header" style="background-color:darkred; color:white; border-radius:5px 5px 0 0;">
                        <h4 class="modal-title">Delete Project Type</h4>
                    </div>

                    <div class="modal-body" id="DeleteModalBody">

                    </div>

                    <div dir="rtl" class="modal-footer" style="text-align:left;">
                        <button class="btn btn-default" type="button" style="width:80px;" data-dismiss="modal">Reject</button>
                        <button type="submit" class="btn" style="width:80px; color:white; background-color:darkred;">
                            Accept
                        </button>
                    </div>

                </form>

            </div>
        </div>
    </div>
    @Html.Partial("_Modal", new BootstrapModel { ID = "modal-action", Size = BootstrapModel.ModalSize.Large })
    @section DMSScripts{
        <script>
        $(document).ready(function () {
           var myobj = '@Html.Raw(Json.Serialize(Model))';
            var dpjson = JSON.parse(myobj);
            console.log(dpjson);

            $("#grid").kendoGrid({
                dataSource: {
                    data: dpjson,
                    pageSize: dpjson.length
                },
                height: 550,
                filterable: true,
                groupable: true,
                sortable: true,
                toolbar: ["pdf", "search","excel"],

                pageable: {
                    refresh: true,
                    pageSizes: true,
                    buttonCount: 5
                },
                columns: [{
                    field: "id",
                    title: "id"
                }, {
                    field: "projectType",
                    width: 150,
                    filterable: {
                        multi: true
                        },
                    title: "Project Type"
                }, {
                    field: "projectTypePersian",
                    width: 150,
                    title: "Persian title"
                },



                    {
                        command: [
                            {
                                name: "del",
                                text: "Delete",
                                click: function (e) {
                                    // command button click handler
                                    var item = this.dataItem($(e.currentTarget).closest("tr"));
                                    url = "/DMSArea/ProjectType/DeleteProjectType";
                                    $.ajax({
                                        url: url,
                                        data: { id: item.id },
                                        type: 'Get',
                                        success: function (result) {
                                            $('#DeleteModalBody').html(result);
                                            $("#myModaldeletor").modal("show");
                                        },
                                        error: function (xhr, status) {
                                            alert(status);
                                        }
                                    });
                                }
                            },
                            {
                                name: "edit",
                                text: "Edit",
                                click: function (e) {
                                    // command button click handler
                                    var item = this.dataItem($(e.currentTarget).closest("tr"));
                                    console.log(item )
                                    window.location.href = '@Url.Action("EditProjectType", "ProjectType")/' + item.id;
                                }
                            },

                        ]
                    }
                ]

            });
            var grid = $("#grid").data("kendoGrid");
            grid.hideColumn("id");

            //$("#grid").data("kendoGrid").wrapper.find(".k-grid-header-wrap").off("scroll.kendoGrid");

        });


        </script>
    }

DPEnergy/Areas/DMSArea/Views/ProjectType/_deleteProjectType.cshtml
@model DPEnergy.DataModelLayer.Entities.DMS.BasicInformation.D_ProjectType
@{
    Layout = null;
}

<div class="modal-body form-horizontal">
    Are you sure you want to delete
    <span style="font-weight:bold;">@Model.ProjectType</span>
    ?
</div>
<input type="hidden" asp-for="Id" />